### PR TITLE
Fix rmq multichannel

### PR DESCRIPTION
**Pull request by holytshirt**
Creating this pull request to start a discussion on this topic

### CODE REVIEW

**Comment by iancooper** [comment]
Apart from the build fail. IMO pull and then when @ianbattersby and I get some time we can do a little pairing session around moving some of the responsibilities out of this class and into collaborators. But we should prioritize fixing the bug over making the code clean for now

**Comment by ianbattersby** [comment]
This needs squashing before merging ;) #SeeJiraTicket

**Comment by ianbattersby** [comment]
This needs rebasing and merge conflicts resolving, moving to new branch and closing this.

**Comment by ianbattersby** [comment]
This is now in [fix-rmqmultchannel2](https://github.com/iancooper/Paramore/compare/fix-rmqmultchannel2?expand=1)

**Pull request closed without merging**
